version: '3'

services:
  postgres_db:
    container_name: my_db
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust

    ports:
      - '5432:5432'

    # volumes:
    #   - db:/var/lib/postgresql/data

  redis:
    image: redis:7.0.11-alpine

  backend:
    container_name: backend
    build:
      dockerfile: Dockerfile.server.dev
      context: ./server
    volumes:
      - /usr/app/node_modules
      - ./server:/usr/app

    # configuration variables
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=postgres_db
      - POSTGRES_DATABASE=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_HOST_AUTH_METHOD=trust

  frontend:
    container_name: frontend
    build:
      dockerfile: Dockerfile.client.dev
      context: ./client

    volumes:
      - /usr/app/node_modules
      - ./client:/usr/app

  worker:
    container_name: worker
    build:
      dockerfile: Dockerfile.worker.dev
      context: ./worker

    volumes:
      - /usr/app/node_modules
      - ./worker:/usr/app

  nginx:
    restart: always
    container_name: nginx
    build:
      dockerfile: Dockerfile.nginx.dev
      context: ./nginx
    ports:
      - '3050:80'
